[package]
name = "boseiju_wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
boseiju_lexer = { workspace = true, features = ["spanned_tree"] }
boseiju_parser = { workspace = true, features = ["spanned_tree"] }
boseiju_span = { workspace = true }
boseiju_tree = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
idris = { workspace = true }
