# https://doc.rust-lang.org/cargo/reference/workspaces.html
[workspace]
members = [
    "boseiju_bin",
    "boseiju_lexer",
    "boseiju_span",
    "boseiju_tree",
#   "boseiju_wasm",
    "idris",
    "krark",
    "mtg_cardbase",
    "mtg_data",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
authors = ["Virgile HENRY"]
description = "Vector embedding for MTG cards"
documentation = "https://github.com/VirgileHenry/brainstorm"
edition = "2024"

[workspace.dependencies]
# Own crates as dependencies
boseiju_lexer = { path = "boseiju_lexer" }
boseiju_span = { path = "boseiju_span" }
boseiju_tree = { path = "boseiju_tree" }
# boseiju_wasm = { path = "boseiju_wasm" }
idris = { path = "idris" }
idris_derive = { path = "idris_derive" }
krark = { path = "krark" }
mtg_data = { path = "mtg_data" }
mtg_cardbase = { path = "mtg_cardbase" }

# Additional dependencies
arrayvec = { version = "0.7.6", features = ["serde"] }
lazy_static = "1.5.0"
regex = "1.11.3"
serde = { version = "1.0.221", features=["derive"] }
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["serde"] }
