pub const AXEBANE_FEROX____AXEBANE_FEROX: crate::Card = crate::Card {
object: "card",
id: "9f7b2c39-64c1-4edf-a912-8b8bd3a24557",
oracle_id: "c68b1863-304a-4bf1-9703-88cdbedfeb66",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Axebane Ferox // Axebane Ferox",
lang: "en",
released_at: "2024-02-09",
uri: "https://api.scryfall.com/cards/9f7b2c39-64c1-4edf-a912-8b8bd3a24557",
scryfall_uri: "https://scryfall.com/card/amkm/13/axebane-ferox-axebane-ferox?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("pauper", "not_legal"),("standardbrawl", "not_legal"),("penny", "not_legal"),("alchemy", "not_legal"),("gladiator", "not_legal"),("premodern", "not_legal"),("historic", "not_legal"),("pioneer", "not_legal"),("future", "not_legal"),("brawl", "not_legal"),("vintage", "not_legal"),("commander", "not_legal"),("legacy", "not_legal"),("duel", "not_legal"),("timeless", "not_legal"),("standard", "not_legal"),("oldschool", "not_legal"),("predh", "not_legal"),("paupercommander", "not_legal"),("modern", "not_legal"),("oathbreaker", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "cebbaa6a-05a8-4737-889c-0dee42e6af33",
set: "amkm",
set_name: "Murders at Karlov Manor Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/cebbaa6a-05a8-4737-889c-0dee42e6af33",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aamkm&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/amkm?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/9f7b2c39-64c1-4edf-a912-8b8bd3a24557/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac68b1863-304a-4bf1-9703-88cdbedfeb66&unique=prints",
collector_number: "13",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Maxime Minard",
artist_ids: Some(&["a9065769-afcd-4e54-a3c0-5809e7b4108b", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DAxebane%2BFerox%2B%252F%252F%2BAxebane%2BFerox"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DAxebane%2BFerox%2B%252F%252F%2BAxebane%2BFerox"), ("edhrec", "https://edhrec.com/route/?cc=Axebane+Ferox"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DAxebane%2BFerox%26view%3Dgrid"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Axebane+Ferox&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Axebane+Ferox&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
