pub const BALAMB_GARDEN__SEED_ACADEMY____BALAMB_GARDEN__AIRBORNE: crate::Card = crate::Card {
object: "card",
id: "001e9f20-5b15-41cb-bf82-46172decc235",
oracle_id: "8b84fec5-617c-4088-8250-2ba1f1f9479a",
multiverse_ids: Some(&[]),
mtgo_id: Some(141511),
arena_id: None,
tcgplayer_id: Some(634012),
cardmarket_id: Some(827001),
name: "Balamb Garden, SeeD Academy // Balamb Garden, Airborne",
lang: "en",
released_at: "2025-06-13",
uri: "https://api.scryfall.com/cards/001e9f20-5b15-41cb-bf82-46172decc235",
scryfall_uri: "https://scryfall.com/card/fin/272/balamb-garden-seed-academy-balamb-garden-airborne?utm_source=api",
layout: "transform",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Land — Town // Legendary Artifact — Vehicle",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &["G", "U", ],
keywords: &["Flying", "Transform", "Crew", ],
produced_mana: Some(&["G", "U", ]),
legalities: &[("vintage", "legal"),("alchemy", "legal"),("predh", "not_legal"),("pioneer", "legal"),("oathbreaker", "legal"),("pauper", "not_legal"),("historic", "legal"),("future", "legal"),("brawl", "legal"),("paupercommander", "not_legal"),("oldschool", "not_legal"),("commander", "legal"),("modern", "legal"),("premodern", "not_legal"),("gladiator", "legal"),("penny", "legal"),("standard", "legal"),("duel", "legal"),("standardbrawl", "legal"),("timeless", "legal"),("legacy", "legal"),],
games: &["paper", "arena", "mtgo", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "d7beb4b7-e1ff-4d35-ab07-5700f17ea1ea",
set: "fin",
set_name: "Final Fantasy",
set_type: "expansion",
set_uri: "https://api.scryfall.com/sets/d7beb4b7-e1ff-4d35-ab07-5700f17ea1ea",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Afin&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/fin?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/001e9f20-5b15-41cb-bf82-46172decc235/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8b84fec5-617c-4088-8250-2ba1f1f9479a&unique=prints",
collector_number: "272",
digital: false,
rarity: "rare",
card_back_id: None,
artist: "Jonas De Ro",
artist_ids: Some(&["561ebf9e-8d93-4b57-8156-8826d0c19601", ]),
illustration_id: None,
border_color: "black",
frame: "2015",
frame_effects: Some(&["legendary", ]),
security_stamp: Some("triangle"),
full_art: false,
textless: false,
booster: true,
story_spotlight: false,
edhrec_rank: Some(9593),
penny_rank: None,
preview: Some(crate::Preview {
source: "CGMagazine",
source_uri: "https://www.cgmagonline.com/articles/previews/mtg-final-fantasy-homebases/",
previewed_at: "2025-05-23",
}),
prices: crate::Prices {
usd: Some("0.37"),
usd_foil: Some("0.76"),
usd_etched: None,
eur: Some("0.31"),
eur_foil: Some("0.83"),
tix: Some("0.02"),
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DBalamb%2BGarden%252C%2BSeeD%2BAcademy%2B%252F%252F%2BBalamb%2BGarden%252C%2BAirborne"), ("edhrec", "https://edhrec.com/route/?cc=Balamb+Garden%2C+SeeD+Academy"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DBalamb%2BGarden%252C%2BSeeD%2BAcademy%2B%252F%252F%2BBalamb%2BGarden%252C%2BAirborne"), ]),
purchase_uris: Some(&[("cardmarket", "https://www.cardmarket.com/en/Magic/Products?idProduct=827001&referrer=scryfall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fproduct%2F634012%3Fpage%3D1"), ("cardhoarder", "https://www.cardhoarder.com/cards/141511?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
