pub const DUNGEON_OF_THE_MAD_MAGE: crate::Card = crate::Card {
object: "card",
id: "6f509dbe-6ec7-4438-ab36-e20be46c9922",
oracle_id: "30d0398c-bf5a-4b30-936f-afdb5a109b4b",
multiverse_ids: Some(&[530447, ]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: Some(245106),
cardmarket_id: None,
name: "Dungeon of the Mad Mage",
lang: "en",
released_at: "2021-07-23",
uri: "https://api.scryfall.com/cards/6f509dbe-6ec7-4438-ab36-e20be46c9922",
scryfall_uri: "https://scryfall.com/card/tafr/20/dungeon-of-the-mad-mage?utm_source=api",
layout: "normal",
highres_image: true,
image_status: "highres_scan",
image_uris: Some(crate::ImageUris {
small: "https://cards.scryfall.io/small/front/6/f/6f509dbe-6ec7-4438-ab36-e20be46c9922.jpg?1753983585",
normal: "https://cards.scryfall.io/normal/front/6/f/6f509dbe-6ec7-4438-ab36-e20be46c9922.jpg?1753983585",
large: "https://cards.scryfall.io/large/front/6/f/6f509dbe-6ec7-4438-ab36-e20be46c9922.jpg?1753983585",
png: "https://cards.scryfall.io/png/front/6/f/6f509dbe-6ec7-4438-ab36-e20be46c9922.png?1753983585",
art_crop: "https://cards.scryfall.io/art_crop/front/6/f/6f509dbe-6ec7-4438-ab36-e20be46c9922.jpg?1753983585",
border_crop: "https://cards.scryfall.io/border_crop/front/6/f/6f509dbe-6ec7-4438-ab36-e20be46c9922.jpg?1753983585",
}),
mana_cost: Some(""),
cmc: 0.0,
type_line: "Dungeon",
oracle_text: Some("Yawning Portal — You gain 1 life. (Leads to: Dungeon Level)\nDungeon Level — Scry 1. (Leads to: Goblin Bazaar, Twisted Caverns)\nGoblin Bazaar — Create a Treasure token. (Leads to: Lost Level)\nTwisted Caverns — Target creature can't attack until your next turn. (Leads to: Lost Level)\nLost Level — Scry 2. (Leads to: Runestone Caverns, Muiral's Graveyard)\nRunestone Caverns — Exile the top two cards of your library. You may play them. (Leads to: Deep Mines)\nMuiral's Graveyard — Create two 1/1 black Skeleton creature tokens. (Leads to: Deep Mines)\nDeep Mines — Scry 3. (Leads to: Mad Wizard's Lair)\nMad Wizard's Lair — Draw three cards and reveal them. You may cast one of them without paying its mana cost."),
power: None,
toughness: None,
colors: Some(&[]),
color_identity: &[],
keywords: &["Treasure", "Scry", ],
produced_mana: None,
legalities: &[("alchemy", "not_legal"),("timeless", "not_legal"),("oathbreaker", "not_legal"),("legacy", "not_legal"),("modern", "not_legal"),("commander", "not_legal"),("future", "not_legal"),("pauper", "not_legal"),("gladiator", "not_legal"),("premodern", "not_legal"),("vintage", "not_legal"),("duel", "not_legal"),("paupercommander", "not_legal"),("historic", "not_legal"),("brawl", "not_legal"),("predh", "not_legal"),("standard", "not_legal"),("oldschool", "not_legal"),("standardbrawl", "not_legal"),("penny", "not_legal"),("pioneer", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "68e8eca4-2c75-4f44-8519-59489e76b719",
set: "tafr",
set_name: "Adventures in the Forgotten Realms Tokens",
set_type: "token",
set_uri: "https://api.scryfall.com/sets/68e8eca4-2c75-4f44-8519-59489e76b719",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Atafr&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/tafr?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/6f509dbe-6ec7-4438-ab36-e20be46c9922/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A30d0398c-bf5a-4b30-936f-afdb5a109b4b&unique=prints",
collector_number: "20",
digital: false,
rarity: "common",
card_back_id: Some("0aeebaf5-8c7d-4636-9e82-8c27447861f7"),
artist: "",
artist_ids: None,
illustration_id: None,
border_color: "black",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: Some(crate::Preview {
source: "Wizards of the Coast",
source_uri: "https://magic.wizards.com/en/articles/archive/feature/adventures-forgotten-realms-mechanics-2021-06-24",
previewed_at: "2021-06-24",
}),
prices: crate::Prices {
usd: Some("4.18"),
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DDungeon%2Bof%2Bthe%2BMad%2BMage"), ("gatherer", "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=530447&printed=false"), ("edhrec", "https://edhrec.com/route/?cc=Dungeon+of+the+Mad+Mage"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DDungeon%2Bof%2Bthe%2BMad%2BMage"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fproduct%2F245106%3Fpage%3D1"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Dungeon+of+the+Mad+Mage&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Dungeon+of+the+Mad+Mage&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
