pub const GLIMPSE_THE_CORE____GLIMPSE_THE_CORE: crate::Card = crate::Card {
object: "card",
id: "910731d5-3f1a-4d17-8290-1138ec903a64",
oracle_id: "ac1ac86a-0652-4627-aff5-1f93336692c7",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Glimpse the Core // Glimpse the Core",
lang: "en",
released_at: "2023-11-17",
uri: "https://api.scryfall.com/cards/910731d5-3f1a-4d17-8290-1138ec903a64",
scryfall_uri: "https://scryfall.com/card/alci/25/glimpse-the-core-glimpse-the-core?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("predh", "not_legal"),("brawl", "not_legal"),("modern", "not_legal"),("pioneer", "not_legal"),("historic", "not_legal"),("paupercommander", "not_legal"),("pauper", "not_legal"),("standardbrawl", "not_legal"),("duel", "not_legal"),("standard", "not_legal"),("future", "not_legal"),("oathbreaker", "not_legal"),("premodern", "not_legal"),("penny", "not_legal"),("gladiator", "not_legal"),("vintage", "not_legal"),("timeless", "not_legal"),("legacy", "not_legal"),("alchemy", "not_legal"),("commander", "not_legal"),("oldschool", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "1135b292-4f02-4eec-8623-a1b7aee474df",
set: "alci",
set_name: "The Lost Caverns of Ixalan Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/1135b292-4f02-4eec-8623-a1b7aee474df",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aalci&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/alci?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/910731d5-3f1a-4d17-8290-1138ec903a64/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aac1ac86a-0652-4627-aff5-1f93336692c7&unique=prints",
collector_number: "25",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Francisco Miyara",
artist_ids: Some(&["fa64fc53-a243-4a94-a4d2-97625ea24b4f", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Glimpse+the+Core"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DGlimpse%2Bthe%2BCore%2B%252F%252F%2BGlimpse%2Bthe%2BCore"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DGlimpse%2Bthe%2BCore%2B%252F%252F%2BGlimpse%2Bthe%2BCore"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DGlimpse%2Bthe%2BCore%26view%3Dgrid"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Glimpse+the+Core&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Glimpse+the+Core&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
