pub const HANWEIR_MILITIA_CAPTAIN____WESTVALE_CULT_LEADER: crate::Card = crate::Card {
object: "card",
id: "7e137566-5033-48e8-88ba-65e3821b3cec",
oracle_id: "2d8eba16-cfca-4a38-bde0-6ee36c67231a",
multiverse_ids: Some(&[409759, 409760, ]),
mtgo_id: Some(59908),
arena_id: None,
tcgplayer_id: Some(115988),
cardmarket_id: Some(289091),
name: "Hanweir Militia Captain // Westvale Cult Leader",
lang: "en",
released_at: "2016-04-08",
uri: "https://api.scryfall.com/cards/7e137566-5033-48e8-88ba-65e3821b3cec",
scryfall_uri: "https://scryfall.com/card/soi/21/hanweir-militia-captain-westvale-cult-leader?utm_source=api",
layout: "transform",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 2.0,
type_line: "Creature — Human Soldier // Creature — Human Cleric",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &["W", ],
keywords: &["Transform", ],
produced_mana: None,
legalities: &[("standard", "not_legal"),("brawl", "legal"),("commander", "legal"),("penny", "legal"),("paupercommander", "not_legal"),("duel", "legal"),("historic", "legal"),("legacy", "legal"),("oathbreaker", "legal"),("alchemy", "not_legal"),("oldschool", "not_legal"),("predh", "not_legal"),("modern", "legal"),("pioneer", "legal"),("standardbrawl", "not_legal"),("gladiator", "legal"),("premodern", "not_legal"),("future", "not_legal"),("vintage", "legal"),("pauper", "not_legal"),("timeless", "legal"),],
games: &["paper", "mtgo", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "5e914d7e-c1e9-446c-a33d-d093c02b2743",
set: "soi",
set_name: "Shadows over Innistrad",
set_type: "expansion",
set_uri: "https://api.scryfall.com/sets/5e914d7e-c1e9-446c-a33d-d093c02b2743",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Asoi&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/soi?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/7e137566-5033-48e8-88ba-65e3821b3cec/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A2d8eba16-cfca-4a38-bde0-6ee36c67231a&unique=prints",
collector_number: "21",
digital: false,
rarity: "rare",
card_back_id: None,
artist: "David Palumbo",
artist_ids: Some(&["04ce1c75-e30c-4b7a-8cb0-b53e4ecc2f39", ]),
illustration_id: None,
border_color: "black",
frame: "2015",
frame_effects: Some(&["sunmoondfc", ]),
security_stamp: Some("oval"),
full_art: false,
textless: false,
booster: true,
story_spotlight: false,
edhrec_rank: Some(7379),
penny_rank: Some(2712),
preview: None,
prices: crate::Prices {
usd: Some("0.41"),
usd_foil: Some("1.45"),
usd_etched: None,
eur: Some("0.66"),
eur_foil: Some("1.77"),
tix: Some("0.02"),
},
related_uris: Some(&[("gatherer", "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=409759&printed=false"), ("edhrec", "https://edhrec.com/route/?cc=Hanweir+Militia+Captain"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DHanweir%2BMilitia%2BCaptain%2B%252F%252F%2BWestvale%2BCult%2BLeader"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DHanweir%2BMilitia%2BCaptain%2B%252F%252F%2BWestvale%2BCult%2BLeader"), ]),
purchase_uris: Some(&[("cardmarket", "https://www.cardmarket.com/en/Magic/Products?idProduct=289091&referrer=scryfall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards/59908?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fproduct%2F115988%3Fpage%3D1"), ]),
};
