pub const HYDROELECTRIC_SPECIMEN____HYDROELECTRIC_LABORATORY: crate::Card = crate::Card {
object: "card",
id: "8689ecd7-e9a6-458b-99d2-6dbaca527f00",
oracle_id: "573151f0-00d4-4a8a-8a09-745c5f376532",
multiverse_ids: Some(&[661759, ]),
mtgo_id: Some(126505),
arena_id: Some(90806),
tcgplayer_id: Some(553181),
cardmarket_id: Some(772468),
name: "Hydroelectric Specimen // Hydroelectric Laboratory",
lang: "en",
released_at: "2024-06-14",
uri: "https://api.scryfall.com/cards/8689ecd7-e9a6-458b-99d2-6dbaca527f00",
scryfall_uri: "https://scryfall.com/card/mh3/240/hydroelectric-specimen-hydroelectric-laboratory?utm_source=api",
layout: "modal_dfc",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 3.0,
type_line: "Creature — Weird // Land",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &["U", ],
keywords: &["Flash", ],
produced_mana: Some(&["U", ]),
legalities: &[("predh", "not_legal"),("pioneer", "not_legal"),("duel", "legal"),("oldschool", "not_legal"),("future", "not_legal"),("modern", "legal"),("historic", "legal"),("gladiator", "legal"),("oathbreaker", "legal"),("standard", "not_legal"),("legacy", "legal"),("standardbrawl", "not_legal"),("timeless", "legal"),("paupercommander", "not_legal"),("penny", "not_legal"),("alchemy", "not_legal"),("premodern", "not_legal"),("brawl", "legal"),("pauper", "not_legal"),("commander", "legal"),("vintage", "legal"),],
games: &["paper", "mtgo", "arena", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "3ed80bb6-77e8-4aa7-8262-95377a38aba1",
set: "mh3",
set_name: "Modern Horizons 3",
set_type: "draft_innovation",
set_uri: "https://api.scryfall.com/sets/3ed80bb6-77e8-4aa7-8262-95377a38aba1",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Amh3&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/mh3?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/8689ecd7-e9a6-458b-99d2-6dbaca527f00/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A573151f0-00d4-4a8a-8a09-745c5f376532&unique=prints",
collector_number: "240",
digital: false,
rarity: "uncommon",
card_back_id: None,
artist: "Raoul Vitale",
artist_ids: Some(&["c7c15d49-f84b-4d98-9a34-e80e8347b756", ]),
illustration_id: None,
border_color: "black",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: true,
story_spotlight: false,
edhrec_rank: Some(898),
penny_rank: None,
preview: Some(crate::Preview {
source: "Gamerbraves",
source_uri: "https://www.gamerbraves.com/mtg-modern-horizons-3-introduces-hydroelectric-specimen-and-hydroelectric-laboratory-double-faced-card/",
previewed_at: "2024-05-28",
}),
prices: crate::Prices {
usd: Some("1.07"),
usd_foil: Some("1.67"),
usd_etched: None,
eur: Some("0.85"),
eur_foil: Some("1.64"),
tix: Some("0.04"),
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DHydroelectric%2BSpecimen%2B%252F%252F%2BHydroelectric%2BLaboratory"), ("gatherer", "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=661759&printed=false"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DHydroelectric%2BSpecimen%2B%252F%252F%2BHydroelectric%2BLaboratory"), ("edhrec", "https://edhrec.com/route/?cc=Hydroelectric+Specimen"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fproduct%2F553181%3Fpage%3D1"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products?idProduct=772468&referrer=scryfall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards/126505?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
