pub const KHERU_GOLDKEEPER____KHERU_GOLDKEEPER: crate::Card = crate::Card {
object: "card",
id: "0cba3e94-b945-44b9-b22d-dc2d8ac56776",
oracle_id: "68b1f20d-b04d-401f-a88f-20d5e065de48",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Kheru Goldkeeper // Kheru Goldkeeper",
lang: "en",
released_at: "2025-04-11",
uri: "https://api.scryfall.com/cards/0cba3e94-b945-44b9-b22d-dc2d8ac56776",
scryfall_uri: "https://scryfall.com/card/atdm/36/kheru-goldkeeper-kheru-goldkeeper?utm_source=api",
layout: "art_series",
highres_image: false,
image_status: "lowres",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("standardbrawl", "not_legal"),("vintage", "not_legal"),("premodern", "not_legal"),("future", "not_legal"),("historic", "not_legal"),("timeless", "not_legal"),("gladiator", "not_legal"),("legacy", "not_legal"),("commander", "not_legal"),("penny", "not_legal"),("duel", "not_legal"),("pauper", "not_legal"),("oathbreaker", "not_legal"),("pioneer", "not_legal"),("modern", "not_legal"),("brawl", "not_legal"),("alchemy", "not_legal"),("standard", "not_legal"),("paupercommander", "not_legal"),("oldschool", "not_legal"),("predh", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "8e84d6a0-e29e-41da-884c-ece6a65e84be",
set: "atdm",
set_name: "Tarkir: Dragonstorm Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/8e84d6a0-e29e-41da-884c-ece6a65e84be",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aatdm&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/atdm?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/0cba3e94-b945-44b9-b22d-dc2d8ac56776/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A68b1f20d-b04d-401f-a88f-20d5e065de48&unique=prints",
collector_number: "36",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Jarel Threat",
artist_ids: Some(&["0fd89fbd-bd59-4ded-890e-731a8982f278", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Kheru+Goldkeeper"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DKheru%2BGoldkeeper%2B%252F%252F%2BKheru%2BGoldkeeper"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DKheru%2BGoldkeeper%2B%252F%252F%2BKheru%2BGoldkeeper"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DKheru%2BGoldkeeper%26view%3Dgrid"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Kheru+Goldkeeper&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Kheru+Goldkeeper&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
