pub const LILAH__UNDEFEATED_SLICKSHOT____LILAH__UNDEFEATED_SLICKSHOT: crate::Card = crate::Card {
object: "card",
id: "7aa9c0bd-57fb-4769-af9c-cc3ef1172c1e",
oracle_id: "2990e10c-7ef7-4291-a9a8-58560f7730d9",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Lilah, Undefeated Slickshot // Lilah, Undefeated Slickshot",
lang: "en",
released_at: "2024-04-19",
uri: "https://api.scryfall.com/cards/7aa9c0bd-57fb-4769-af9c-cc3ef1172c1e",
scryfall_uri: "https://scryfall.com/card/aotj/26/lilah-undefeated-slickshot-lilah-undefeated-slickshot?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("gladiator", "not_legal"),("timeless", "not_legal"),("brawl", "not_legal"),("predh", "not_legal"),("commander", "not_legal"),("standardbrawl", "not_legal"),("premodern", "not_legal"),("oldschool", "not_legal"),("duel", "not_legal"),("vintage", "not_legal"),("paupercommander", "not_legal"),("historic", "not_legal"),("oathbreaker", "not_legal"),("pauper", "not_legal"),("future", "not_legal"),("modern", "not_legal"),("alchemy", "not_legal"),("pioneer", "not_legal"),("legacy", "not_legal"),("penny", "not_legal"),("standard", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "9d2325c7-06a4-4404-8bbf-1fcdf02f15ac",
set: "aotj",
set_name: "Outlaws of Thunder Junction Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/9d2325c7-06a4-4404-8bbf-1fcdf02f15ac",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aaotj&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/aotj?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/7aa9c0bd-57fb-4769-af9c-cc3ef1172c1e/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A2990e10c-7ef7-4291-a9a8-58560f7730d9&unique=prints",
collector_number: "26",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Andreas Zafiratos",
artist_ids: Some(&["e2f13a9a-57c5-40de-81d4-3b0723899cdf", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Lilah%2C+Undefeated+Slickshot"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DLilah%252C%2BUndefeated%2BSlickshot%2B%252F%252F%2BLilah%252C%2BUndefeated%2BSlickshot"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DLilah%252C%2BUndefeated%2BSlickshot%2B%252F%252F%2BLilah%252C%2BUndefeated%2BSlickshot"), ]),
purchase_uris: Some(&[("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Lilah%2C+Undefeated+Slickshot&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Lilah%2C+Undefeated+Slickshot&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DLilah%252C%2BUndefeated%2BSlickshot%26view%3Dgrid"), ]),
};
