pub const METAMORPHIC_BLAST____METAMORPHIC_BLAST: crate::Card = crate::Card {
object: "card",
id: "4ae95b72-d9b7-4315-ba92-035201f26b03",
oracle_id: "12f47641-33d8-4e40-9cc4-bb3a90fd5ca1",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Metamorphic Blast // Metamorphic Blast",
lang: "en",
released_at: "2024-04-19",
uri: "https://api.scryfall.com/cards/4ae95b72-d9b7-4315-ba92-035201f26b03",
scryfall_uri: "https://scryfall.com/card/aotj/7/metamorphic-blast-metamorphic-blast?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("brawl", "not_legal"),("alchemy", "not_legal"),("timeless", "not_legal"),("gladiator", "not_legal"),("standard", "not_legal"),("paupercommander", "not_legal"),("standardbrawl", "not_legal"),("premodern", "not_legal"),("historic", "not_legal"),("penny", "not_legal"),("oathbreaker", "not_legal"),("vintage", "not_legal"),("commander", "not_legal"),("pauper", "not_legal"),("future", "not_legal"),("duel", "not_legal"),("modern", "not_legal"),("oldschool", "not_legal"),("predh", "not_legal"),("pioneer", "not_legal"),("legacy", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "9d2325c7-06a4-4404-8bbf-1fcdf02f15ac",
set: "aotj",
set_name: "Outlaws of Thunder Junction Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/9d2325c7-06a4-4404-8bbf-1fcdf02f15ac",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aaotj&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/aotj?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/4ae95b72-d9b7-4315-ba92-035201f26b03/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A12f47641-33d8-4e40-9cc4-bb3a90fd5ca1&unique=prints",
collector_number: "7",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Michal Ivan",
artist_ids: Some(&["89ba58cb-84a6-480b-a86c-d8ae57df2834", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DMetamorphic%2BBlast%2B%252F%252F%2BMetamorphic%2BBlast"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DMetamorphic%2BBlast%2B%252F%252F%2BMetamorphic%2BBlast"), ("edhrec", "https://edhrec.com/route/?cc=Metamorphic+Blast"), ]),
purchase_uris: Some(&[("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Metamorphic+Blast&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DMetamorphic%2BBlast%26view%3Dgrid"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Metamorphic+Blast&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
