pub const MITE_OVERSEER____MITE_OVERSEER: crate::Card = crate::Card {
object: "card",
id: "d05df9d0-dbe3-41ab-9d99-3cbd25f39c77",
oracle_id: "992178ad-1b6c-49b1-990a-26c78c67fe51",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Mite Overseer // Mite Overseer",
lang: "en",
released_at: "2023-02-03",
uri: "https://api.scryfall.com/cards/d05df9d0-dbe3-41ab-9d99-3cbd25f39c77",
scryfall_uri: "https://scryfall.com/card/aone/4/mite-overseer-mite-overseer?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("oathbreaker", "not_legal"),("modern", "not_legal"),("alchemy", "not_legal"),("paupercommander", "not_legal"),("future", "not_legal"),("pauper", "not_legal"),("premodern", "not_legal"),("brawl", "not_legal"),("historic", "not_legal"),("standardbrawl", "not_legal"),("pioneer", "not_legal"),("gladiator", "not_legal"),("timeless", "not_legal"),("penny", "not_legal"),("oldschool", "not_legal"),("standard", "not_legal"),("duel", "not_legal"),("predh", "not_legal"),("legacy", "not_legal"),("vintage", "not_legal"),("commander", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "7024a171-1b99-49dc-8777-0db9c552eb06",
set: "aone",
set_name: "Phyrexia: All Will Be One Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/7024a171-1b99-49dc-8777-0db9c552eb06",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aaone&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/aone?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/d05df9d0-dbe3-41ab-9d99-3cbd25f39c77/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A992178ad-1b6c-49b1-990a-26c78c67fe51&unique=prints",
collector_number: "4",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Néstor Ossandón Leal",
artist_ids: Some(&["7a6f1667-a8ac-47f5-a302-f71cb54b2adf", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DMite%2BOverseer%2B%252F%252F%2BMite%2BOverseer"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DMite%2BOverseer%2B%252F%252F%2BMite%2BOverseer"), ("edhrec", "https://edhrec.com/route/?cc=Mite+Overseer"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DMite%2BOverseer%26view%3Dgrid"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Mite+Overseer&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Mite+Overseer&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
