pub const PHYREXIAN_OBLITERATOR____PHYREXIAN_OBLITERATOR: crate::Card = crate::Card {
object: "card",
id: "bedc4ca4-1714-40ff-9211-dc1b78276f8d",
oracle_id: "ba648d45-5b9a-4674-abab-8907dc026e9d",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Phyrexian Obliterator // Phyrexian Obliterator",
lang: "en",
released_at: "2023-02-03",
uri: "https://api.scryfall.com/cards/bedc4ca4-1714-40ff-9211-dc1b78276f8d",
scryfall_uri: "https://scryfall.com/card/aone/71/phyrexian-obliterator-phyrexian-obliterator?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("pioneer", "not_legal"),("brawl", "not_legal"),("oldschool", "not_legal"),("vintage", "not_legal"),("commander", "not_legal"),("standard", "not_legal"),("penny", "not_legal"),("historic", "not_legal"),("modern", "not_legal"),("oathbreaker", "not_legal"),("future", "not_legal"),("legacy", "not_legal"),("alchemy", "not_legal"),("paupercommander", "not_legal"),("duel", "not_legal"),("gladiator", "not_legal"),("standardbrawl", "not_legal"),("timeless", "not_legal"),("premodern", "not_legal"),("predh", "not_legal"),("pauper", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "7024a171-1b99-49dc-8777-0db9c552eb06",
set: "aone",
set_name: "Phyrexia: All Will Be One Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/7024a171-1b99-49dc-8777-0db9c552eb06",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aaone&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/aone?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/bedc4ca4-1714-40ff-9211-dc1b78276f8d/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aba648d45-5b9a-4674-abab-8907dc026e9d&unique=prints",
collector_number: "71",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Yu-ki Nishimoto",
artist_ids: Some(&["6ced75be-30a5-45c6-90ee-9316101b0d8c", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Phyrexian+Obliterator"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DPhyrexian%2BObliterator%2B%252F%252F%2BPhyrexian%2BObliterator"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DPhyrexian%2BObliterator%2B%252F%252F%2BPhyrexian%2BObliterator"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DPhyrexian%2BObliterator%26view%3Dgrid"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Phyrexian+Obliterator&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Phyrexian+Obliterator&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
