pub const RACERS__RING____RACERS__RING: crate::Card = crate::Card {
object: "card",
id: "fac52739-7245-4a1c-9fee-5523d63378fd",
oracle_id: "0e83fba6-6a94-4c58-8ef1-d866732d5eb4",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Racers' Ring // Racers' Ring",
lang: "en",
released_at: "2022-04-29",
uri: "https://api.scryfall.com/cards/fac52739-7245-4a1c-9fee-5523d63378fd",
scryfall_uri: "https://scryfall.com/card/asnc/80/racers-ring-racers-ring?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("timeless", "not_legal"),("alchemy", "not_legal"),("historic", "not_legal"),("pioneer", "not_legal"),("modern", "not_legal"),("premodern", "not_legal"),("penny", "not_legal"),("commander", "not_legal"),("vintage", "not_legal"),("standardbrawl", "not_legal"),("duel", "not_legal"),("oathbreaker", "not_legal"),("paupercommander", "not_legal"),("brawl", "not_legal"),("predh", "not_legal"),("gladiator", "not_legal"),("legacy", "not_legal"),("future", "not_legal"),("standard", "not_legal"),("pauper", "not_legal"),("oldschool", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "32d16b44-d39f-42af-80d8-470700c7259c",
set: "asnc",
set_name: "New Capenna Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/32d16b44-d39f-42af-80d8-470700c7259c",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aasnc&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/asnc?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/fac52739-7245-4a1c-9fee-5523d63378fd/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0e83fba6-6a94-4c58-8ef1-d866732d5eb4&unique=prints",
collector_number: "80",
digital: false,
rarity: "common",
card_back_id: None,
artist: "David Curtis",
artist_ids: Some(&["f50507f9-9add-48a8-8eed-dec6f0608832", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Racers%27+Ring"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DRacers%2527%2BRing%2B%252F%252F%2BRacers%2527%2BRing"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DRacers%2527%2BRing%2B%252F%252F%2BRacers%2527%2BRing"), ]),
purchase_uris: Some(&[("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Racers%27+Ring&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Racers%27+Ring&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DRacers%2527%2BRing%26view%3Dgrid"), ]),
};
