pub const REALLY_CHARMING_PRINCE: crate::Card = crate::Card {
object: "card",
id: "c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a",
oracle_id: "bb3a8e94-b9f8-41dd-96a1-80c826d325ea",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Really Charming Prince",
lang: "en",
released_at: "2023-09-23",
uri: "https://api.scryfall.com/cards/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a",
scryfall_uri: "https://scryfall.com/card/unk/RU02d/really-charming-prince?utm_source=api",
layout: "normal",
highres_image: true,
image_status: "highres_scan",
image_uris: Some(crate::ImageUris {
small: "https://cards.scryfall.io/small/front/c/4/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a.jpg?1729980065",
normal: "https://cards.scryfall.io/normal/front/c/4/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a.jpg?1729980065",
large: "https://cards.scryfall.io/large/front/c/4/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a.jpg?1729980065",
png: "https://cards.scryfall.io/png/front/c/4/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a.png?1729980065",
art_crop: "https://cards.scryfall.io/art_crop/front/c/4/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a.jpg?1729980065",
border_crop: "https://cards.scryfall.io/border_crop/front/c/4/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a.jpg?1729980065",
}),
mana_cost: Some("{1}{U}"),
cmc: 2.0,
type_line: "Creature — Faerie Noble",
oracle_text: Some("Flying\nWhen Really Charming Prince enters the battlefield, choose one of the following four cards at random: Piracy Charm, Sapphire Charm, Trickery Charm, and Vision Charm. You may create a copy of the chosen card and cast that copy without paying its mana cost."),
power: Some("2"),
toughness: Some("1"),
colors: Some(&["U", ]),
color_identity: &["U", ],
keywords: &["Flying", ],
produced_mana: None,
legalities: &[("premodern", "not_legal"),("future", "not_legal"),("oathbreaker", "not_legal"),("standard", "not_legal"),("penny", "not_legal"),("standardbrawl", "not_legal"),("alchemy", "not_legal"),("vintage", "not_legal"),("gladiator", "not_legal"),("pioneer", "not_legal"),("pauper", "not_legal"),("modern", "not_legal"),("historic", "not_legal"),("oldschool", "not_legal"),("predh", "not_legal"),("brawl", "not_legal"),("legacy", "not_legal"),("commander", "not_legal"),("paupercommander", "not_legal"),("duel", "not_legal"),("timeless", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: false,
nonfoil: true,
finishes: &["nonfoil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "d2703c4f-66b6-438d-9368-ebb55aa12e78",
set: "unk",
set_name: "Unknown Event",
set_type: "funny",
set_uri: "https://api.scryfall.com/sets/d2703c4f-66b6-438d-9368-ebb55aa12e78",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aunk&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/unk?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/c45d0d5f-b802-4cb3-8caa-88ad6bf42c6a/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Abb3a8e94-b9f8-41dd-96a1-80c826d325ea&unique=prints",
collector_number: "RU02d",
digital: false,
rarity: "rare",
card_back_id: Some("0aeebaf5-8c7d-4636-9e82-8c27447861f7"),
artist: "",
artist_ids: None,
illustration_id: None,
border_color: "black",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DReally%2BCharming%2BPrince"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DReally%2BCharming%2BPrince"), ("edhrec", "https://edhrec.com/route/?cc=Really+Charming+Prince"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DReally%2BCharming%2BPrince%26view%3Dgrid"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Really+Charming+Prince&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Really+Charming+Prince&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
