pub const RONA__TOLARIAN_OBLITERATOR____RONA__TOLARIAN_OBLITERATOR: crate::Card = crate::Card {
object: "card",
id: "51d81af9-5c07-491e-a27b-9b67b1f71496",
oracle_id: "82cf0f22-4662-4c0d-b8ef-3008d741248b",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Rona, Tolarian Obliterator // Rona, Tolarian Obliterator",
lang: "en",
released_at: "2023-04-21",
uri: "https://api.scryfall.com/cards/51d81af9-5c07-491e-a27b-9b67b1f71496",
scryfall_uri: "https://scryfall.com/card/amom/17/rona-tolarian-obliterator-rona-tolarian-obliterator?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("duel", "not_legal"),("oathbreaker", "not_legal"),("penny", "not_legal"),("legacy", "not_legal"),("gladiator", "not_legal"),("standard", "not_legal"),("predh", "not_legal"),("paupercommander", "not_legal"),("pioneer", "not_legal"),("brawl", "not_legal"),("commander", "not_legal"),("standardbrawl", "not_legal"),("oldschool", "not_legal"),("modern", "not_legal"),("pauper", "not_legal"),("vintage", "not_legal"),("premodern", "not_legal"),("alchemy", "not_legal"),("historic", "not_legal"),("future", "not_legal"),("timeless", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "f835c2e6-0f96-4a98-9e6c-5d2836ce1c54",
set: "amom",
set_name: "March of the Machine Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/f835c2e6-0f96-4a98-9e6c-5d2836ce1c54",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aamom&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/amom?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/51d81af9-5c07-491e-a27b-9b67b1f71496/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A82cf0f22-4662-4c0d-b8ef-3008d741248b&unique=prints",
collector_number: "17",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Victor Adame Minguez",
artist_ids: Some(&["bd8f7368-5b10-4554-b6b8-d052c6aca89f", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Rona%2C+Tolarian+Obliterator"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DRona%252C%2BTolarian%2BObliterator%2B%252F%252F%2BRona%252C%2BTolarian%2BObliterator"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DRona%252C%2BTolarian%2BObliterator%2B%252F%252F%2BRona%252C%2BTolarian%2BObliterator"), ]),
purchase_uris: Some(&[("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Rona%2C+Tolarian+Obliterator&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Rona%2C+Tolarian+Obliterator&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DRona%252C%2BTolarian%2BObliterator%26view%3Dgrid"), ]),
};
