pub const SCAVENGER_REGENT____SCAVENGER_REGENT: crate::Card = crate::Card {
object: "card",
id: "5bb74a4c-05bf-47df-ac7d-2e67f2d13312",
oracle_id: "55551eae-5572-4f56-ba5c-7932935d2608",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Scavenger Regent // Scavenger Regent",
lang: "en",
released_at: "2025-04-11",
uri: "https://api.scryfall.com/cards/5bb74a4c-05bf-47df-ac7d-2e67f2d13312",
scryfall_uri: "https://scryfall.com/card/atdm/45/scavenger-regent-scavenger-regent?utm_source=api",
layout: "art_series",
highres_image: false,
image_status: "lowres",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("premodern", "not_legal"),("brawl", "not_legal"),("future", "not_legal"),("legacy", "not_legal"),("timeless", "not_legal"),("commander", "not_legal"),("modern", "not_legal"),("pioneer", "not_legal"),("vintage", "not_legal"),("pauper", "not_legal"),("penny", "not_legal"),("oldschool", "not_legal"),("alchemy", "not_legal"),("paupercommander", "not_legal"),("gladiator", "not_legal"),("duel", "not_legal"),("predh", "not_legal"),("standard", "not_legal"),("oathbreaker", "not_legal"),("standardbrawl", "not_legal"),("historic", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "8e84d6a0-e29e-41da-884c-ece6a65e84be",
set: "atdm",
set_name: "Tarkir: Dragonstorm Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/8e84d6a0-e29e-41da-884c-ece6a65e84be",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aatdm&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/atdm?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/5bb74a4c-05bf-47df-ac7d-2e67f2d13312/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A55551eae-5572-4f56-ba5c-7932935d2608&unique=prints",
collector_number: "45",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Allen Douglas",
artist_ids: Some(&["e17f248e-6a47-4889-b048-a646739923b0", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DScavenger%2BRegent%2B%252F%252F%2BScavenger%2BRegent"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DScavenger%2BRegent%2B%252F%252F%2BScavenger%2BRegent"), ("edhrec", "https://edhrec.com/route/?cc=Scavenger+Regent"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DScavenger%2BRegent%26view%3Dgrid"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Scavenger+Regent&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Scavenger+Regent&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
