pub const SUSPEND____SUSPEND: crate::Card = crate::Card {
object: "card",
id: "625268e5-589a-4ac1-a83d-37ae9bb6ecb3",
oracle_id: "3cb38557-c14b-46a4-8c8d-1ee549abf4ec",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Suspend // Suspend",
lang: "en",
released_at: "2021-06-18",
uri: "https://api.scryfall.com/cards/625268e5-589a-4ac1-a83d-37ae9bb6ecb3",
scryfall_uri: "https://scryfall.com/card/amh2/23/suspend-suspend?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("oldschool", "not_legal"),("standardbrawl", "not_legal"),("future", "not_legal"),("brawl", "not_legal"),("penny", "not_legal"),("historic", "not_legal"),("timeless", "not_legal"),("paupercommander", "not_legal"),("duel", "not_legal"),("premodern", "not_legal"),("legacy", "not_legal"),("predh", "not_legal"),("standard", "not_legal"),("alchemy", "not_legal"),("commander", "not_legal"),("pauper", "not_legal"),("oathbreaker", "not_legal"),("vintage", "not_legal"),("modern", "not_legal"),("gladiator", "not_legal"),("pioneer", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "95671546-fd82-43e2-966f-eba5968f629b",
set: "amh2",
set_name: "Modern Horizons 2 Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/95671546-fd82-43e2-966f-eba5968f629b",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aamh2&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/amh2?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/625268e5-589a-4ac1-a83d-37ae9bb6ecb3/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A3cb38557-c14b-46a4-8c8d-1ee549abf4ec&unique=prints",
collector_number: "23",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Lake Hurwitz",
artist_ids: Some(&["3677c64b-55e6-4a0d-a952-bdbb05531220", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Suspend"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DSuspend%2B%252F%252F%2BSuspend"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DSuspend%2B%252F%252F%2BSuspend"), ]),
purchase_uris: Some(&[("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Suspend&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DSuspend%26view%3Dgrid"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Suspend&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
