pub const TOM_BOMBADIL____TOM_BOMBADIL: crate::Card = crate::Card {
object: "card",
id: "4d927796-97d5-4648-ad88-6169115dd0fd",
oracle_id: "102ae626-3a4d-4d78-a2a6-f760ba02dd88",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Tom Bombadil // Tom Bombadil",
lang: "en",
released_at: "2023-06-23",
uri: "https://api.scryfall.com/cards/4d927796-97d5-4648-ad88-6169115dd0fd",
scryfall_uri: "https://scryfall.com/card/altr/26/tom-bombadil-tom-bombadil?utm_source=api",
layout: "art_series",
highres_image: false,
image_status: "lowres",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("timeless", "not_legal"),("predh", "not_legal"),("standardbrawl", "not_legal"),("modern", "not_legal"),("gladiator", "not_legal"),("alchemy", "not_legal"),("oldschool", "not_legal"),("pauper", "not_legal"),("pioneer", "not_legal"),("duel", "not_legal"),("premodern", "not_legal"),("historic", "not_legal"),("standard", "not_legal"),("legacy", "not_legal"),("penny", "not_legal"),("commander", "not_legal"),("oathbreaker", "not_legal"),("paupercommander", "not_legal"),("future", "not_legal"),("vintage", "not_legal"),("brawl", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "af23b3cb-d42f-426b-90f0-8a07fcb302b8",
set: "altr",
set_name: "Tales of Middle-earth Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/af23b3cb-d42f-426b-90f0-8a07fcb302b8",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aaltr&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/altr?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/4d927796-97d5-4648-ad88-6169115dd0fd/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A102ae626-3a4d-4d78-a2a6-f760ba02dd88&unique=prints",
collector_number: "26",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Dmitry Burmak",
artist_ids: Some(&["9872f5c0-274a-48ce-a9ad-6f0d5654e29c", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("edhrec", "https://edhrec.com/route/?cc=Tom+Bombadil"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DTom%2BBombadil%2B%252F%252F%2BTom%2BBombadil"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DTom%2BBombadil%2B%252F%252F%2BTom%2BBombadil"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DTom%2BBombadil%26view%3Dgrid"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Tom+Bombadil&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Tom+Bombadil&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
