pub const VOLTAIC_VISIONARY____VOLT_CHARGED_BERSERKER: crate::Card = crate::Card {
object: "card",
id: "a8b85386-462b-46f8-9412-fd47ed1dc1da",
oracle_id: "8ffe9e3f-fd9f-4d8b-9467-4cd301e3c8b4",
multiverse_ids: Some(&[541042, 541043, ]),
mtgo_id: Some(94712),
arena_id: Some(78990),
tcgplayer_id: Some(253532),
cardmarket_id: Some(582693),
name: "Voltaic Visionary // Volt-Charged Berserker",
lang: "en",
released_at: "2021-11-19",
uri: "https://api.scryfall.com/cards/a8b85386-462b-46f8-9412-fd47ed1dc1da",
scryfall_uri: "https://scryfall.com/card/vow/183/voltaic-visionary-volt-charged-berserker?utm_source=api",
layout: "transform",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 2.0,
type_line: "Creature — Human Wizard // Creature — Human Berserker",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &["R", ],
keywords: &["Transform", ],
produced_mana: None,
legalities: &[("oathbreaker", "legal"),("standardbrawl", "not_legal"),("standard", "not_legal"),("future", "not_legal"),("gladiator", "legal"),("pioneer", "legal"),("legacy", "legal"),("duel", "legal"),("alchemy", "not_legal"),("vintage", "legal"),("oldschool", "not_legal"),("premodern", "not_legal"),("modern", "legal"),("commander", "legal"),("historic", "legal"),("pauper", "not_legal"),("brawl", "legal"),("predh", "not_legal"),("timeless", "legal"),("paupercommander", "not_legal"),("penny", "not_legal"),],
games: &["arena", "paper", "mtgo", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "8144b676-569f-4716-8005-bc8f0778f3fa",
set: "vow",
set_name: "Innistrad: Crimson Vow",
set_type: "expansion",
set_uri: "https://api.scryfall.com/sets/8144b676-569f-4716-8005-bc8f0778f3fa",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Avow&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/vow?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/a8b85386-462b-46f8-9412-fd47ed1dc1da/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8ffe9e3f-fd9f-4d8b-9467-4cd301e3c8b4&unique=prints",
collector_number: "183",
digital: false,
rarity: "uncommon",
card_back_id: None,
artist: "Francisco Miyara",
artist_ids: Some(&["fa64fc53-a243-4a94-a4d2-97625ea24b4f", ]),
illustration_id: None,
border_color: "black",
frame: "2015",
frame_effects: Some(&["sunmoondfc", ]),
security_stamp: None,
full_art: false,
textless: false,
booster: true,
story_spotlight: false,
edhrec_rank: Some(24121),
penny_rank: Some(7822),
preview: Some(crate::Preview {
source: "André Manenti",
source_uri: "https://twitter.com/andremanentii/status/1455550927918751746",
previewed_at: "2021-11-02",
}),
prices: crate::Prices {
usd: Some("0.04"),
usd_foil: Some("0.02"),
usd_etched: None,
eur: Some("0.04"),
eur_foil: Some("0.09"),
tix: Some("0.03"),
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DVoltaic%2BVisionary%2B%252F%252F%2BVolt-Charged%2BBerserker"), ("gatherer", "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=541042&printed=false"), ("edhrec", "https://edhrec.com/route/?cc=Voltaic+Visionary"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DVoltaic%2BVisionary%2B%252F%252F%2BVolt-Charged%2BBerserker"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fproduct%2F253532%3Fpage%3D1"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products?idProduct=582693&referrer=scryfall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards/94712?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ]),
};
