pub const WEAVER_OF_BLOSSOMS____BLOSSOM_CLAD_WEREWOLF: crate::Card = crate::Card {
object: "card",
id: "73bf2a0a-b97d-4b90-abd6-d1755734ea15",
oracle_id: "a64ecae7-0b09-48e1-8108-89442547ffda",
multiverse_ids: Some(&[541094, 541095, ]),
mtgo_id: Some(94816),
arena_id: Some(79042),
tcgplayer_id: Some(253461),
cardmarket_id: Some(582111),
name: "Weaver of Blossoms // Blossom-Clad Werewolf",
lang: "en",
released_at: "2021-11-19",
uri: "https://api.scryfall.com/cards/73bf2a0a-b97d-4b90-abd6-d1755734ea15",
scryfall_uri: "https://scryfall.com/card/vow/226/weaver-of-blossoms-blossom-clad-werewolf?utm_source=api",
layout: "transform",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 3.0,
type_line: "Creature — Human Werewolf // Creature — Werewolf",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &["G", ],
keywords: &["Daybound", "Nightbound", ],
produced_mana: Some(&["B", "G", "R", "U", "W", ]),
legalities: &[("future", "not_legal"),("pioneer", "legal"),("oathbreaker", "legal"),("standardbrawl", "not_legal"),("vintage", "legal"),("penny", "not_legal"),("alchemy", "not_legal"),("paupercommander", "legal"),("gladiator", "legal"),("duel", "legal"),("oldschool", "not_legal"),("modern", "legal"),("premodern", "not_legal"),("pauper", "legal"),("legacy", "legal"),("standard", "not_legal"),("historic", "legal"),("commander", "legal"),("brawl", "legal"),("predh", "not_legal"),("timeless", "legal"),],
games: &["arena", "paper", "mtgo", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "8144b676-569f-4716-8005-bc8f0778f3fa",
set: "vow",
set_name: "Innistrad: Crimson Vow",
set_type: "expansion",
set_uri: "https://api.scryfall.com/sets/8144b676-569f-4716-8005-bc8f0778f3fa",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Avow&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/vow?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/73bf2a0a-b97d-4b90-abd6-d1755734ea15/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aa64ecae7-0b09-48e1-8108-89442547ffda&unique=prints",
collector_number: "226",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Andrey Kuzinskiy",
artist_ids: Some(&["c04ff0b2-67a1-4238-82f7-6c67de734b56", ]),
illustration_id: None,
border_color: "black",
frame: "2015",
frame_effects: Some(&["sunmoondfc", ]),
security_stamp: None,
full_art: false,
textless: false,
booster: true,
story_spotlight: false,
edhrec_rank: Some(8992),
penny_rank: Some(15324),
preview: Some(crate::Preview {
source: "Grey Ogre Games",
source_uri: "https://www.facebook.com/greyogregames/posts/1997336577093093",
previewed_at: "2021-11-02",
}),
prices: crate::Prices {
usd: Some("0.10"),
usd_foil: Some("0.28"),
usd_etched: None,
eur: Some("0.10"),
eur_foil: Some("0.13"),
tix: Some("0.03"),
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DWeaver%2Bof%2BBlossoms%2B%252F%252F%2BBlossom-Clad%2BWerewolf"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DWeaver%2Bof%2BBlossoms%2B%252F%252F%2BBlossom-Clad%2BWerewolf"), ("edhrec", "https://edhrec.com/route/?cc=Weaver+of+Blossoms"), ("gatherer", "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=541094&printed=false"), ]),
purchase_uris: Some(&[("cardhoarder", "https://www.cardhoarder.com/cards/94816?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fproduct%2F253461%3Fpage%3D1"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products?idProduct=582111&referrer=scryfall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
