pub const WISH____WISH: crate::Card = crate::Card {
object: "card",
id: "7677f694-e611-416d-8e9e-86d3b33b4c76",
oracle_id: "020e5b34-c546-4abe-a412-36aa1713b241",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Wish // Wish",
lang: "en",
released_at: "2021-07-23",
uri: "https://api.scryfall.com/cards/7677f694-e611-416d-8e9e-86d3b33b4c76",
scryfall_uri: "https://scryfall.com/card/aafr/50/wish-wish?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("historic", "not_legal"),("future", "not_legal"),("standardbrawl", "not_legal"),("alchemy", "not_legal"),("premodern", "not_legal"),("penny", "not_legal"),("pauper", "not_legal"),("brawl", "not_legal"),("oldschool", "not_legal"),("modern", "not_legal"),("standard", "not_legal"),("commander", "not_legal"),("oathbreaker", "not_legal"),("duel", "not_legal"),("vintage", "not_legal"),("legacy", "not_legal"),("paupercommander", "not_legal"),("predh", "not_legal"),("timeless", "not_legal"),("gladiator", "not_legal"),("pioneer", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "8696ef63-3530-4453-a0f8-7fd3bd09306a",
set: "aafr",
set_name: "Adventures in the Forgotten Realms Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/8696ef63-3530-4453-a0f8-7fd3bd09306a",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aaafr&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/aafr?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/7677f694-e611-416d-8e9e-86d3b33b4c76/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A020e5b34-c546-4abe-a412-36aa1713b241&unique=prints",
collector_number: "50",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Ekaterina Burmak",
artist_ids: Some(&["2a9f3780-fcc8-4ec5-b403-ee1d1370d3b4", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DWish%2B%252F%252F%2BWish"), ("edhrec", "https://edhrec.com/route/?cc=Wish"), ("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DWish%2B%252F%252F%2BWish"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DWish%26view%3Dgrid"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Wish&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Wish&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
