pub const YOUTHFUL_VALKYRIE____YOUTHFUL_VALKYRIE: crate::Card = crate::Card {
object: "card",
id: "70dedcd2-cbb9-447f-9ee7-c281cc3ba86f",
oracle_id: "170893bd-f656-4bdd-9e28-1dc84117b3cf",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Youthful Valkyrie // Youthful Valkyrie",
lang: "en",
released_at: "2024-11-15",
uri: "https://api.scryfall.com/cards/70dedcd2-cbb9-447f-9ee7-c281cc3ba86f",
scryfall_uri: "https://scryfall.com/card/afdn/28/youthful-valkyrie-youthful-valkyrie?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("duel", "not_legal"),("pauper", "not_legal"),("predh", "not_legal"),("standardbrawl", "not_legal"),("commander", "not_legal"),("oathbreaker", "not_legal"),("standard", "not_legal"),("paupercommander", "not_legal"),("vintage", "not_legal"),("premodern", "not_legal"),("brawl", "not_legal"),("future", "not_legal"),("modern", "not_legal"),("historic", "not_legal"),("timeless", "not_legal"),("pioneer", "not_legal"),("legacy", "not_legal"),("penny", "not_legal"),("alchemy", "not_legal"),("gladiator", "not_legal"),("oldschool", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "dae4bf74-97f7-40a6-ac46-54b6b0d8a58d",
set: "afdn",
set_name: "Foundations Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/dae4bf74-97f7-40a6-ac46-54b6b0d8a58d",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aafdn&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/afdn?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/70dedcd2-cbb9-447f-9ee7-c281cc3ba86f/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A170893bd-f656-4bdd-9e28-1dc84117b3cf&unique=prints",
collector_number: "28",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Néstor Ossandón Leal",
artist_ids: Some(&["7a6f1667-a8ac-47f5-a302-f71cb54b2adf", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DYouthful%2BValkyrie%2B%252F%252F%2BYouthful%2BValkyrie"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DYouthful%2BValkyrie%2B%252F%252F%2BYouthful%2BValkyrie"), ("edhrec", "https://edhrec.com/route/?cc=Youthful+Valkyrie"), ]),
purchase_uris: Some(&[("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Youthful+Valkyrie&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Youthful+Valkyrie&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DYouthful%2BValkyrie%26view%3Dgrid"), ]),
};
