pub const ZOPANDREL__HUNGER_DOMINUS____ZOPANDREL__HUNGER_DOMINUS: crate::Card = crate::Card {
object: "card",
id: "9d5515cc-7081-4526-ae84-b34be338005f",
oracle_id: "3e548643-1c5a-491d-af89-546ef29cd9ec",
multiverse_ids: Some(&[]),
mtgo_id: None,
arena_id: None,
tcgplayer_id: None,
cardmarket_id: None,
name: "Zopandrel, Hunger Dominus // Zopandrel, Hunger Dominus",
lang: "en",
released_at: "2023-02-03",
uri: "https://api.scryfall.com/cards/9d5515cc-7081-4526-ae84-b34be338005f",
scryfall_uri: "https://scryfall.com/card/aone/44/zopandrel-hunger-dominus-zopandrel-hunger-dominus?utm_source=api",
layout: "art_series",
highres_image: true,
image_status: "highres_scan",
image_uris: None,
mana_cost: None,
cmc: 0.0,
type_line: "Card // Card",
oracle_text: None,
power: None,
toughness: None,
colors: None,
color_identity: &[],
keywords: &[],
produced_mana: None,
legalities: &[("pauper", "not_legal"),("gladiator", "not_legal"),("alchemy", "not_legal"),("duel", "not_legal"),("oldschool", "not_legal"),("oathbreaker", "not_legal"),("vintage", "not_legal"),("penny", "not_legal"),("future", "not_legal"),("brawl", "not_legal"),("premodern", "not_legal"),("legacy", "not_legal"),("timeless", "not_legal"),("historic", "not_legal"),("commander", "not_legal"),("paupercommander", "not_legal"),("modern", "not_legal"),("standard", "not_legal"),("standardbrawl", "not_legal"),("pioneer", "not_legal"),("predh", "not_legal"),],
games: &["paper", ],
reserved: false,
game_changer: Some(false),
foil: true,
nonfoil: true,
finishes: &["nonfoil", "foil", ],
oversized: false,
promo: false,
reprint: false,
variation: false,
set_id: "7024a171-1b99-49dc-8777-0db9c552eb06",
set: "aone",
set_name: "Phyrexia: All Will Be One Art Series",
set_type: "memorabilia",
set_uri: "https://api.scryfall.com/sets/7024a171-1b99-49dc-8777-0db9c552eb06",
set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aaone&unique=prints",
scryfall_set_uri: "https://scryfall.com/sets/aone?utm_source=api",
rulings_uri: "https://api.scryfall.com/cards/9d5515cc-7081-4526-ae84-b34be338005f/rulings",
prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A3e548643-1c5a-491d-af89-546ef29cd9ec&unique=prints",
collector_number: "44",
digital: false,
rarity: "common",
card_back_id: None,
artist: "Antonio José Manzanedo",
artist_ids: Some(&["74986d28-0001-4a78-827c-e490b325d0e3", ]),
illustration_id: None,
border_color: "borderless",
frame: "2015",
frame_effects: None,
security_stamp: None,
full_art: false,
textless: false,
booster: false,
story_spotlight: false,
edhrec_rank: None,
penny_rank: None,
preview: None,
prices: crate::Prices {
usd: None,
usd_foil: None,
usd_etched: None,
eur: None,
eur_foil: None,
tix: None,
},
related_uris: Some(&[("tcgplayer_infinite_decks", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Fdecks&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fdecks%3FproductLineName%3Dmagic%26q%3DZopandrel%252C%2BHunger%2BDominus%2B%252F%252F%2BZopandrel%252C%2BHunger%2BDominus"), ("edhrec", "https://edhrec.com/route/?cc=Zopandrel%2C+Hunger+Dominus"), ("tcgplayer_infinite_articles", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer.com%2Fsearch%2Farticles&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Farticles%3FproductLineName%3Dmagic%26q%3DZopandrel%252C%2BHunger%2BDominus%2B%252F%252F%2BZopandrel%252C%2BHunger%2BDominus"), ]),
purchase_uris: Some(&[("tcgplayer", "https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2Fsearch%2Fmagic%2Fproduct%3FproductLineName%3Dmagic%26q%3DZopandrel%252C%2BHunger%2BDominus%26view%3Dgrid"), ("cardhoarder", "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Zopandrel%2C+Hunger+Dominus&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"), ("cardmarket", "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Zopandrel%2C+Hunger+Dominus&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall"), ]),
};
